# Site settings
title: Ocupop Project Template
email: dev@ocupop.com
url: "http://client_url.com"
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:


# Collections
collections:
  examples:
    output: true
    permalink: /examples/:path/

defaults:
  -
    scope:
      type: 'examples'
    values:
      layout: example
      # variable_name: value

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder

_array_structures:
  navigation_links:
    - label: Navigation Links
      icon: link
      value:
        link:
        title:
        sub_navigation_links:
  sub_navigation_links:
    - label: Sub Navigation Links
      icon: link
      value:
        link:
        title:
  page_sections:
    - label: One Column Section
      icon: web
      value:
        _type: 1_column
        section_html:
    - label: Two Column Section
      icon: web
      value:
        _type: 2_column
        left_column_html:
        right_column_html:
    - label: Gallery
      icon: collections
      value:
        _type: gallery      
        gallery_images:
  gallery_images:
    - label: Gallery Images
      icon: collections
      value:
        image:
        title:         


